"""init_db

Revision ID: 7add046994b4
Revises: 
Create Date: 2026-02-03 12:48:57.572896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7add046994b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nome'), 'categoria', ['nome'], unique=True)
    op.create_table('centrotreinamento',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('proprietario', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centrotreinamento_endereco'), 'centrotreinamento', ['endereco'], unique=False)
    op.create_index(op.f('ix_centrotreinamento_nome'), 'centrotreinamento', ['nome'], unique=False)
    op.create_index(op.f('ix_centrotreinamento_proprietario'), 'centrotreinamento', ['proprietario'], unique=False)
    op.create_table('atleta',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('centro_treinamento_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['centro_treinamento_id'], ['centrotreinamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atleta_cpf'), 'atleta', ['cpf'], unique=True)
    op.create_index(op.f('ix_atleta_nome'), 'atleta', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atleta_nome'), table_name='atleta')
    op.drop_index(op.f('ix_atleta_cpf'), table_name='atleta')
    op.drop_table('atleta')
    op.drop_index(op.f('ix_centrotreinamento_proprietario'), table_name='centrotreinamento')
    op.drop_index(op.f('ix_centrotreinamento_nome'), table_name='centrotreinamento')
    op.drop_index(op.f('ix_centrotreinamento_endereco'), table_name='centrotreinamento')
    op.drop_table('centrotreinamento')
    op.drop_index(op.f('ix_categoria_nome'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
